### ISSUE TITLE
Uploading large collections incremental issues.

### ISSUE THREAD

**Issue by Sp5rky** [Ravencentric/juicenet-cli#66]
When working with large TV shows that count above 100 they are labeled as "S01E09," "S01E10," and then inexplicably jump to "S01E100." when it should be "S01E11"

Example
![image](https://github.com/Ravencentric/juicenet-cli/assets/29722511/6ad28519-9a92-437b-95a4-a2dddd9092ed)

**Comment by Ravencentric** [comment]
I think I fixed it. If you encounter it again, feel free to report it with an example list so I can test it.
